#!/bin/bash
# Final build: Use the actual source files to build libnetfilter_queue

set -e

echo "╔══════════════════════════════════════════════════════════╗"
echo "║  Final Build: Using Existing Source Files               ║"
echo "╚══════════════════════════════════════════════════════════╝"
echo ""

cd /tmp/libnetfilter_queue-1.0.5

# Check what source files we have
echo "📁 Checking source files..."
ls -la src/
ls -la include/

# Create minimal config.h (normally generated by configure)
echo "📝 Creating config.h..."
cat > config.h << 'EOF'
/* config.h - minimal configuration for libnetfilter_queue */
#define PACKAGE_NAME "libnetfilter_queue"
#define PACKAGE_VERSION "1.0.5"
#define VERSION "1.0.5"
#define HAVE_LIBNFNETLINK 1
#define HAVE_LIBMNL 0
#define STDC_HEADERS 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRING_H 1
#define HAVE_UNISTD_H 1
EOF

# The actual source is in src/libnetfilter_queue.c
# Headers are in include/libnetfilter_queue/

# Build manually using the source files
echo "🔨 Building library manually..."

# Find the actual source file
SRC_FILE="src/libnetfilter_queue.c"
HEADER_DIR="include/libnetfilter_queue"

if [ ! -f "$SRC_FILE" ]; then
    echo "❌ Source file not found: $SRC_FILE"
    exit 1
fi

echo "Using source: $SRC_FILE"
echo "Using headers: $HEADER_DIR"

# Compile the library with config.h
gcc -fPIC -shared \
    -I. \
    -I./include \
    -I./src \
    -I/usr/include/libnfnetlink \
    -o libnetfilter_queue.so \
    "$SRC_FILE" \
    src/nlmsg.c \
    -L/usr/lib -lnfnetlink \
    -Wl,-soname,libnetfilter_queue.so.1

# Check if build succeeded
if [ ! -f libnetfilter_queue.so ]; then
    echo "❌ Build failed"
    exit 1
fi

echo "✅ Library built: libnetfilter_queue.so"

# Install headers and library
echo "📦 Installing..."
sudo mkdir -p /usr/include/libnetfilter_queue
sudo cp -r include/libnetfilter_queue/* /usr/include/libnetfilter_queue/
sudo cp libnetfilter_queue.so /usr/lib/
sudo ldconfig

# Verify installation
echo "🔍 Verifying installation..."
if [ -f /usr/include/libnetfilter_queue/libnetfilter_queue.h ]; then
    echo "✅ Headers installed"
    ls -la /usr/include/libnetfilter_queue/
else
    echo "❌ Headers not found"
    exit 1
fi

if [ -f /usr/lib/libnetfilter_queue.so ]; then
    echo "✅ Library installed"
    ls -la /usr/lib/libnetfilter_queue.so*
else
    echo "❌ Library not found"
    exit 1
fi

# Install Python package
echo ""
echo "🐍 Installing Python netfilterqueue..."
cd ~/Capstone-Project/backend
source venv/bin/activate

export CFLAGS="-I/usr/include/libnfnetlink -I/usr/include/libnetfilter_queue"
export LDFLAGS="-L/usr/lib -lnfnetlink -lnetfilter_queue"

pip install --no-cache-dir netfilterqueue

# Final verification
echo ""
if python3 -c "import netfilterqueue; print('✅ SUCCESS!')" 2>/dev/null; then
    echo "╔══════════════════════════════════════════════════════════╗"
    echo "║  ✅✅✅ INSTALLATION COMPLETE! ✅✅✅                      ║"
    echo "║                                                          ║"
    echo "║  Network Firewall is ready!                              ║"
    echo "║  Start with: sudo python3 network_firewall.py            ║"
    echo "╚══════════════════════════════════════════════════════════╝"
else
    echo "❌ Python import failed. Checking error..."
    python3 -c "import netfilterqueue" 2>&1
    exit 1
fi
